apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-east-1

vpc:
  id: VPC_ID
  subnets:
    public:
      us-east-1a:
        id: subnet-111111111
      us-east-1d:
        id: subnet-222222222

iam:
  serviceRoleARN: ARN_CLUSTER_ROLE

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    iam:
      instanceRoleARN: ARN_NODE_ROLE
